site_name: Documentation Accèslibre Mobilités
site_url: !ENV SITE_URL
repo_url: https://github.com/MTES-MCT/alm-docs/
repo_name: Github
site_author: Someware, Jungle Bus, Atipy & Adrien Pavie


plugins:
  - search  

theme:
  logo: img/logo_alm_white.png
  favicon: img/favicon.png
  name: material
  language: fr
  features:
    - navigation.indexes
    - navigation.footer
  palette:
    scheme: default
    primary: custom
    accent: custom

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true  
  - admonition
  - md_in_html

nav:
  - Accueil: 'index.md'
  - Le modèle de données: 'datamodel/index.md'
  - Installation:
    - Présentation des composants: 'install/architecture.md'
    - Docker: 'install/docker-compose.md'
  - Utilisation:
    - 'usage/index.md'
    - Imports: 
      - 'usage/imports/index.md'
      - Cheminement: 
        - 'usage/imports/cheminement/index.md'
        - OSM : 'usage/imports/cheminement/imports-cheminement-osm.md'
      - Transport:
        - 'usage/imports/transport/index.md'
        - NeTEx : usage/imports/transport/imports-transport-netex.md
        - OSM : usage/imports/transport/imports-transport-osm.md
      - ERP:
        - 'usage/imports/ERP/index.md'
        - AccesLibre : usage/imports/ERP/imports-erp-acceslibre.md
        - OSM : usage/imports/ERP/imports-erp-osm.md      
    - Éditeur web:
      - 'usage/web/index.md'
      - Graphe : usage/web/graphe.md
      - Astuces avancées : usage/web/astuces.md
    - Application mobile:
      - 'usage/mobile/index.md'
      - Utilisation avancée : usage/mobile/tweak.md
    - Exports: 'usage/exports.md'
    - Publication des données: 
        - 'usage/publish/index.md'
        - Licences: 'usage/publish/licence.md'
  - Accompagnement: 'contact.md'
  - Crédits: 'credits.md'
